import uuid
from datetime import datetime, timedelta
from typing import List
from icalendar import Calendar, Event
from app.models import Deadline

class CalendarService:
    @staticmethod
    def generate_ics(doc_title: str, deadlines: List[Deadline]) -> bytes:
        """Generate a valid .ics calendar file containing all document deadlines."""
        cal = Calendar()
        cal.add('prodid', '-//ClarityAI//Document Deadlines//EN')
        cal.add('version', '2.0')
        cal.add('x-wr-calname', f"ClarityAI - {doc_title} Deadlines")
        
        for d in deadlines:
            event = Event()
            event.add('summary', f"[{doc_title}] {d.title}")
            
            # Parse or estimate date
            due_dt = None
            try:
                # Try ISO format
                due_dt = datetime.fromisoformat(d.due_date.replace("Z", "+00:00"))
            except Exception:
                try:
                    # Try YYYY-MM-DD
                    due_dt = datetime.strptime(d.due_date[:10], "%Y-%m-%d")
                except Exception:
                    # Fallback to current time + 7 days
                    due_dt = datetime.utcnow() + timedelta(days=7)
            
            event.add('dtstart', due_dt)
            event.add('dtend', due_dt + timedelta(hours=1))
            event.add('dtstamp', datetime.utcnow())
            event.add('uid', f"{d.id or uuid.uuid4()}@clarityai.app")
            
            desc = f"Category: {d.category}\n"
            if d.page_number:
                desc += f"Referenced on Page: {d.page_number}\n"
            if d.description:
                desc += f"\nDetails:\n{d.description}\n"
            desc += f"\nGenerated by ClarityAI from document: {doc_title}"
            
            event.add('description', desc)
            cal.add_component(event)
            
        return cal.to_ical()

calendar_service = CalendarService()
